apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBBackup
metadata:
  finalizers:
  - delete-backup
  name: after-import
spec:
  clusterName: elog-plus-cluster
  storageName: s3-tid
  type: logical