apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDBRestore
metadata:
  name: restore1
  namespace: elog-plus
spec:
  clusterName: elog-plus-cluster
  backupName: cron-elog-plus-cluste-20240910190000-zfpzt