name: Build Test
on: 
  workflow_call:
      secrets:
          token:
              required: false
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
    build_and_test:
      runs-on: ubuntu-latest
      outputs:
        found: ${{ steps.check_files.outputs.found }}
      steps:
        - name: Checkout source code
          uses: actions/checkout@v3
        - uses: actions/setup-java@v3
          with:
            distribution: temurin
            java-version: 19
        - name: Build Project
          uses: gradle/gradle-build-action@v2
          env:
            CI: true
          with:
            gradle-version: 7.6
            arguments: assemble
        - name: Check for files
          id: check_files
          run: |
            FILES=$(find . -name 'docker-compose.yml)
            if [ -z "$FILES" ]; then echo 'found=false' >> $GITHUB_ENV; else echo 'found=true' >> $GITHUB_ENV; fi
        - name: Launch test backend
          if: steps.check_files.outputs.found == 'true'
          run: |
            docker compose -f docker-compsoe.yml up -d
        - name: Test Project
          uses: gradle/gradle-build-action@v2
          env:
            CI: true
          with:
            gradle-version: 7.6
            arguments: test
        - name: Sjoutdown test backend
          if: steps.check_files.outputs.found == 'true'
          run: |
            docker compose -f docker-compsoe.yml up -d
    test-using-docker-compose:
        runs-on: ubuntu-latest
        container: 
          image: docker:23.0.0-cli
          volumes: 
            - ${{ github.workspace }}:${{ github.workspace }}
          options: --workdir ${{ github.workspace }}
        needs: build_and_test
        steps:
            # Downloads a copy of the code in your repository before running CI tests
            - name: Check out repository code
              uses: actions/checkout@v3
            - name: Install bash
              run: apk add --no-cache bash
            - name: Execute Tests
              shell: bash
              run: |
                ./execute-test.sh
